bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost port=5432 user=admin password=12345 dbname=restapi_dev sslmode=disable"
session_key = "dzUxjJ985ANTJL0nfGkaTCezerxHjYULKYqBidLlh7CiycJXHe107Lc5EA2OIUQAOJnGMW2FNDrR6yY4b0UiCYQ5nVkKzSe8M9t2sSTL2fVbQYtd0hC4IBFW"
pprof_bind_addr = ":3366"